# Use:
#   sops -e secrets.dec.sops.yaml > secrets.sops.yaml
# to encrypt this file.
# The sample private key to use is in the data.sops.age_key.txt field of this file.
# Put in inside the ~/.config/sops/age/keys.txt file.
# Sample command to do that:
#  gojq -r --yaml-input '.data.sops["age_key.txt"]' ./samples/kustomization/secrets.dec.sops.yaml \
#    >> ~/.config/sops/age/keys.txt
# cSpell: disable
apiVersion: karmafun.dev/v1alpha1
kind: SopsGenerator
metadata:
  name: karmafun-secrets
data:
  argocd:
    admin_password: $2a$10$xdlX460lf/WbJNZU5bBoROj6U7oKgPbEcBrnXaemA6gsCzrAJtQ3y
  chisel:
    AUTH: user:password
  cloudflare:
    apiKey: 597aa3a9f23465a7a2f133fda2b7fd11e82211df
    credentials.json: |
      {"AccountTag":"6b713ba4794bb6898c335a6e5e964bc0","TunnelSecret":"0rGDN8oqEVFWYvtUxPCckKpEMiM9I4bOuUsDXNXJVinSTHWs","TunnelID":"ca955c21-2606-4a5d-b217-341a3d12755e"}
  github:
    oidc_client_secret: 72d2976fcf260480dc3a2c392ef4a1cecba348a8
    password: ghp_yHlZKZnbqd8uyTWL8LIuixxh8KOKViwTcXWJ
    ssh_key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACA4nXPm/isSCn3Jmsj2cqBIRhoZ6ZTegcxgFZhDKJXDTwAAAJgOYygIDmMo
      CAAAAAtzc2gtZWQyNTUxOQAAACA4nXPm/isSCn3Jmsj2cqBIRhoZ6ZTegcxgFZhDKJXDTw
      AAAECApDmEpcj6BVxPhdt2ZJB5llYEcGKmapyGXlg/y9Sjejidc+b+KxIKfcmayPZyoEhG
      GhnplN6BzGAVmEMolcNPAAAAD2FudG9pbmVAbXJ0bi5mcgECAwQFBg==
      -----END OPENSSH PRIVATE KEY-----
    webhook_secret: 3AbUHdd35WE4HzYpk53jvzybY9QW4GDY
  ovh:
    application_secret: 29s5X1U9YjFeRhjwat0gLIunwcsHKPe4
    consumer_key: pZzUg3Ux3mig3V50xOpUPK1BgCNK6Dal
  sops:
    age_key.txt: |
      # created: 2023-01-19T19:41:45Z
      # public key: age166k86d56ejs2ydvaxv2x3vl3wajny6l52dlkncf2k58vztnlecjs0g5jqq
      AGE-SECRET-KEY-15RKTPQCCLWM7EHQ8JEP0TQLUWJAECVP7332M3ZP0RL9R7JT7MZ6SY79V8Q
