apiVersion: karmafun.dev/v1alpha1
kind: SopsGenerator
metadata:
  name: karmafun-secrets
data:
  argocd:
    admin_password: ENC[AES256_GCM,data:vIddYifWSJQIaSdJmYppmamlTFzdmVm660PALJS0y8UAgIXPvy2EWM6JwhjhSCzhFOCY4iVixZkC+KMI,iv:hRBZkNDWaO9mw+vK6Nd/hJJ3L+v42NpLNpis3JpRCkE=,tag:5DWH41dXi5pLqSL4XLUqMQ==,type:str]
  chisel:
    AUTH: ENC[AES256_GCM,data:8raxLERnxLkqyoYyuA==,iv:OeQVdVs4RtY4/Pu8dZDJrFx3JOHf0DoYD8NpEsv2+S8=,tag:KnC1R8abibSQNxfC+EN3jQ==,type:str]
  cloudflare:
    apiKey: ENC[AES256_GCM,data:JDuP5Hreb5szT2Hv+yF36PA4Ug/H5pPmk3WrM4z71Sc1gGxqKyjrqg==,iv:pCbumxEy3hpq9VXQjXjZIah2TdngyiRUYZD5bCdpbFE=,tag:hRgxH5g0K5R85WplSyvyfw==,type:str]
    credentials.json: ENC[AES256_GCM,data:xtDu1DfeLDOCx/OAaGhO0UX8vlZVseT+EbdpYJ3WSuFkNLSm1Eztj41eMkm5mzyQ7t6avGfTHl01bD8+Pq40WxE9pDcrhzITys1OqYaF72G4J0PGgkPn/i+lWyBiYkqYiv/Nb/OdQdXz6tGlcdSdqX31cp99DUvAtl1zxTZQmAZjgOprrNAFusjoSGtWv/Sggp648VbGCGzIjL853ERH0oIcoY2GWQ==,iv:crWaRlmvRQZoeYK3H6RsDpVcqdsR+jsZObCo1PqxQrc=,tag:5FSy2weknuYa4elTRZu7ww==,type:str]
  github:
    oidc_client_secret: ENC[AES256_GCM,data:GO9TW5CJmJO3V/uJTG4jzxoHpaeWCYnO9aftvY1jBNq5c7xx/mHeYg==,iv:PJechZgNZzA/EG/V5fkm3RJmFnZSkew4HjIitUoERFU=,tag:vjRW9k1ZJNMF/Ks5MQTHvQ==,type:str]
    password: ENC[AES256_GCM,data:Vl/J7+7pJ7YZRkHg1JgmcX26THM1gqFIrMaLipmYaJ3r5GgcogIKlA==,iv:LgUi5+blhTMtkIH4w8GVTWKvY5Vba4GCQMyAEMYC7nE=,tag:Mi00QujUjcDfDzHXUJbfkQ==,type:str]
    ssh_key: ENC[AES256_GCM,data:hCr88fuHsJMEaSTTS/8a+mKPWv/1WZmhxPyvhc2BQVn3UzgMT50GmArfDYUNW2uce/1L4Xlk4sIZ9EsXXZizwACCQyT+StbtiJofz186EneujZ/iuKS7ht8eV63rS1Ky0lm7Z4FG+oSRGrRCzVlx/yMM5sLIWkI/q9kiergOzDEKSarRqBBc+VqxlZ9HjjpFdHR03KxtXv1Rl2QbZPcp5kVZwHwpCG09ziDwLQj6zOmfD8nb0LjLtMyXFnMfNemFdSYSa2VrSjz/7wQKiqUxCQxIqr3AeDcdZo4rQjFy6vqgXfvJ2ueyHXBrSmV9jKTWjYaIAr3tT6B2h+rpcMS5ogJePZs4csK/R5OYYYvl28AswFLJb2Vn/U8cIwGK7Q31RxZ62z5nPDT500OoNjp9Qyue2hwO7d2hSUPBfZHO5hpMqG99ZoXF1xBH7mAs0nUjomjnsnvhROsSGV6Z6IITFfdzCFfpO+5f8hjeiM1lyzbz3J8LJWbTExRkgv+3hl49yLJLti1sXd+sv3UEwrf8aG2GWTwQdWLFp782,iv:gzUO46YQLeSQTeOQIxgYaepkJ0q//aioBU6CvjTemqg=,tag:gaV+gw4ijFmGLdkJRB39hA==,type:str]
    webhook_secret: ENC[AES256_GCM,data:E2d1KJloAoVuK9rx1pXhj8DiW1FY99vyrOxgcdGC2PE=,iv:afr+TmQTfyDlGiHcp8NutyHzLF7Daw85knAD6Z5SBAw=,tag:1jf+PKGxUr+tGy4usPZbSg==,type:str]
  ovh:
    application_secret: ENC[AES256_GCM,data:xAnzgMLollE0q0kuFenOYT9pRSgDE3MCTJPep9rLy5E=,iv:QyI/wtqBUL4udEq09z8SdVQsubjv7/3IKRuJyIHKp58=,tag:mzn7OyEWdMT+zR9cqEJ/4w==,type:str]
    consumer_key: ENC[AES256_GCM,data:Ih2RB+/xWaqJtAQ7Ks6SCzRUkw+psPAJ/sv9aslzeMQ=,iv:tUKt0I7JsfHnR/RhHiXaO+vSLOMqJ4KvY7/rk7/os9w=,tag:QXdZgewLFPh0m5G7iSGlTQ==,type:str]
  sops:
    age_key.txt: ENC[AES256_GCM,data:ZVJ3FedI/cmKGFxK7U9/4E9g1YczyMBWYY3xVwe/ZQOVQk+nVRapmWI5pRLSEhMAfcQB2XvQ0t20WSES6YgmpABnZnlQ0HKZfiOdRC4ou36ErYT8Vc8XQ/EAu8kNSwtrdsytL/Cnhzlt6s+J78ddWkXxFiOyIzUp6V44AyFAtJdCJ8zQG//GyBcQc7PK06A4CypCQPMhlWGjk6ABzSdDE2XjviG+QbcsUxFCbkEnCtxln+zDeUerAL0GBDLwmRx5SQwBwyF79NXea+FlD3js6UeNdVsPkPvkCHZTHfYdGzZdETZlf0Wxp7cC4i4dqC6jiWOs7Wj84P4=,iv:iXpIpuVmlVydDQM6ECGDTCjoQUriQ5V8Ng7e6S82oTo=,tag:v+TFuC13iu2TQhB7AQZxZA==,type:str]
sops:
  age:
    - recipient: age166k86d56ejs2ydvaxv2x3vl3wajny6l52dlkncf2k58vztnlecjs0g5jqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZExDSzR6OThwS3hJQ1ZL
        dWhKME1xL3NxZEYzaDhjSUtLcVpCbXdCQlJRCmF0QmlTd0d0bGZRZzNEWHVmMDZu
        OGJCZXZZQkNHajNMMHFHUmJNRncxMjgKLS0tIDV2VlNySlRHVE01RU9Zcno0L3FG
        M3dZUFROdll5RlF5S0VZQlhNMDE2YkkKlxrwjDRvSvJtxpSG8/efXUdlX+jWfC83
        cDAVfOYZYLvKee+qvbj1lJHtKsDXITkmh6pfd2vYPwg/nw7EQdMkBg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T07:36:35Z"
  mac: ENC[AES256_GCM,data:mb+bQpPDc2bvbVlTRTD+M8OaSIgNsKoCm5OH0sBppsA+EN5zOFcI5U+eRcyXdPvqCotTE97NL20yPmQax+n1QoSAzAJytZwbP4Nug7p6dTAFMiSmJSsvTXjPWcO1vwVtTNdf6lok5ky2ercoUXEAkHfmXWq6TReZP/YZtoivkO4=,iv:suotoZWIpQty6h2WFzdLCXdpFrvD3vgK7kgO9XS8LmY=,tag:LIvmtaIFPx9Ha7OEebaS3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
