# Use:
#   sops -e secrets.dec.sops.yaml > secrets.sops.yaml
# to encrypt this file.
# The sample private key to use is in the data.sops.age_key.txt field of this file.
# Put in inside the ~/.config/sops/age/keys.txt file.
# Sample command to do that:
#  gojq -r --yaml-input '.data.sops["age_key.txt"]' ./samples/kustomization/secrets.dec.sops.yaml \
#    >> ~/.config/sops/age/keys.txt
# cSpell: disable
apiVersion: karmafun.dev/v1alpha1
kind: SopsGenerator
metadata:
  name: karmafun-secrets
data:
  argocd:
    admin_password: ENC[AES256_GCM,data:JrBq9DskISVnhyi0aZaCVDJ+UTN9bXnteCnJQhbBgamAQ190ueMVmO94k7kjUdzUd30H9Naut0FX48uY,iv:u9R/B5jZ7N1aVeD2u+PHzS068BJROyWI4dU5ZAo1buU=,tag:LRdseb4hcYA4/0XiBYHzuQ==,type:str]
  chisel:
    AUTH: ENC[AES256_GCM,data:2Q58K1fhJoBF0ZEskQ==,iv:I/7sP+dBRw80K5D/FsWzVkdHrCn1QudX9396zPQso3M=,tag:iPj2Mc6oxhYeELyqARsayQ==,type:str]
  cloudflare:
    apiKey: ENC[AES256_GCM,data:xn63eO71js/IHmdIxGnWnYx6HyyPqiTrSbNrbr8DU+oSAWd/rbjloQ==,iv:wDurg6GVYepbr+nP/lT52/bd7d2TV9HhJmQkQhlREUc=,tag:f8KHOrQnlMHxgU/zYqIRyQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:fz1y0nESGds8EvKhvJu6dQ3dcLCxZS3yT5KVSkynKu9GhuMWIXe5nBXyU0zxcZn42Kc+vg/ktAVwCFUgUMLO1DD3o7cqJRsOYT7OnT7li1QqoEji26JwnyJDJMpO9isTTBuUyeWK5jBrB+5JnUYITXyJKOP3VDtc6/5H7cCixhLQStiphjDtU51RymcG9qSYn4pUVEtCQ4tCrV9xOIQDN+QwhB6Sjg==,iv:SLFHSZb2KMegAlOvi105U41vbdV25dDRSSWWmMeK06E=,tag:ZWbw5rQpyNgn0OWgdqsTrA==,type:str]
  github:
    oidc_client_secret: ENC[AES256_GCM,data:her53A94wV8cmd58oYx68H5CLcDadlbtLGXhJOZKfdC7/kHvG0dPzg==,iv:LTned11WKL0UV1A0OvdRAbgIlpoWZ1OCPFPyymhCup0=,tag:ujJchUF1p2wyGqKwMZ9Egg==,type:str]
    password: ENC[AES256_GCM,data:tOjEY9HWYbunOXcQMkUiIzznVHu+r8bifILtjQR93rH1/sF42mT2eQ==,iv:D50B4YBGD/nOZ5VAiwqPfdAeqnqij6SuPhiM70w3jo4=,tag:3U9kHx4eMVKPNT4evVx8dQ==,type:str]
    ssh_key: ENC[AES256_GCM,data:fxy7CpajssYgUvdPQhKfvNq12hjP5a3axvjDvjY8tcdX6gJX9iv/JWsHFmN1b0j+TAmruAAH9e0GvnJoPOQwM5ZGdzHKS+f46qvApkm18I+GiFpxkzOCmxhv26jCoLzQet2zjwVsaGGPwP8PNN/HqfAfG+6PnPHZm2jmirtUEOTlYNfMVVoQ/jbRaijcYSJASrY5bFBiJXZzSFjs1nCi+217wGv6qHTNKaBRfrE5SdLAEggBgicqT7qJQ7X3FqmGxkp8sRU2tir3x+WU5B5+Z3/Ul0vbTo0St9GC3Xw9EIbGhj8XyEAClDw8d6dSjZK45SMbAbSOFJDz/q2xp+lwwMLxvYEOer/qLYF1EQEuqq3Nb6WVJYCIEBQ9X9l/9hFl24npt6G65uQH4V9fPn5uX4ouo+qYNX7MUD9eGyHoL+rzWVyieOtPeFmaxde4bAxw4ThShvXZ6ekpICT6WrNKnKeWcJP3ggzHS+w7YdBmGOSbby3tzcN9U24c4qotRXcMoc7EP+vJC+n4oobwDlSZeUALzZyQIwVIW0IR,iv:aAGEOrIOVyEHa9hFI0h4jW7RX1CKapLrQE0SawVyY8o=,tag:z5ys+7FTSFLxk2FLYnefjA==,type:str]
    webhook_secret: ENC[AES256_GCM,data:735T9Yg3QcaDX1k/SZVyjVvqMpeoO5Mk3E5hHQ3Wtcs=,iv:zV8w4SfZrrsU6kGadCxgwL2xWHqAgSgQ4WsxO7IU1qA=,tag:KuY5B2/CcGeLHviDLO+Ofw==,type:str]
  ovh:
    application_secret: ENC[AES256_GCM,data:Oi3A5f7JMgT+pql9oTg8J7/Pvcvxl67Il5F+RvFE6Es=,iv:2lSqnePLK5j7xnFpT8vhhXBQQey/yBSNNufdsKKLynA=,tag:rhc4kDup/dPaoWj2WeaB3A==,type:str]
    consumer_key: ENC[AES256_GCM,data:DSizX1Dehk1Eo0q9YgSRt6BFhWwPfkuiBppqc7WX71c=,iv:SV+lru1g2JdRubyT9hhpMGKNHT6zABjISt147VhUxRs=,tag:lK/+BEE2D8FRARX4WVXVFQ==,type:str]
  sops:
    age_key.txt: ENC[AES256_GCM,data:9uCikB5Fw58+uVL9ePingr2OH4c4xdT0+M0eP3FmHtFHAcBWlr6sv213PxYpOuILhB0g2Y++AkDVCs9B/eVDCK92780LdvKBZw+RKgy9BCO0EHYQlH8uZW/vjQC2cxuPcAHqc9olaHdKRtCWza224Ee+ZLrQKN0uMkK88tiTAXjRg3cr4UPLHh6NROG8UrGWZi4lEkKahWJOyDO5co8DY3Zo+mJIjNBqwg9m3W3b0zWOuwxd8C2jcw==,iv:uGKCDwvTLywY38KnwuscWmPNEzHIuBRw36WOiC2Qd7U=,tag:qRNR6q8tEMYspHBm1HKEPA==,type:str]
sops:
  age:
    - recipient: age166k86d56ejs2ydvaxv2x3vl3wajny6l52dlkncf2k58vztnlecjs0g5jqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VitwanBFWkJ5YWlDSllo
        bk15VGJGVytRMk5FWWtVWTduSm1uVk9ReDJNClJvQlprbk5BbGR5WmZBVFF3TVp6
        akJiK3REbHlXdHNVMVdpd2E1MFRoMjgKLS0tIEVacWMzd2JCZ0FjNW56ZWpnd0JD
        MjNiV1RNSEdsR1liOGhQL0hhTGdJREkKFUImRpYZ9BpeylaJrJrKtJ54hcikRJIh
        VaWq5AE//uyT/TclRkzEY6OMrbdmeDKFwu0mOGJS6hWp1oIqLWwWnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T08:48:59Z"
  mac: ENC[AES256_GCM,data:aKtXhLEpzyfM/9KpIC+Ts483jzjs7pPu6zEHwdXljPu9Ez59BvcYD6Knm4JoVH78VzU6DDDz+cuykwg+p+bNbReLilWAgyd0iNjCEEvcJ8dCira5cpKVagHuD98tTyY4ALjXr9/H52sPh/ygmV/BM8hZJMdwuGFH/mmp4FtxtMU=,iv:Vvt1YQ1o6iEZpLcliVUO27qjmvka6ui8CXit1x7F+5I=,tag:eDumSd7Pqzh5Cefz7Bh1Ug==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
