# cSpell: disable
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      "github-actions":
        patterns:
          - "*" # Group all GitHub Actions dependencies together
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      "github-actions":
        patterns:
          - "*" # Group all GitHub Actions dependencies together
