# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
# cSpell: words bindir nfpms trimpath lunwind
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    # We limit on these architectures because these are the ones for which KCL is provided.
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.KarmafunVersion={{.Version}} -X main.Commit={{.Commit}} -X
        main.BuildDate={{ .CommitDate }} -X main.BuiltBy=goreleaser
    binary: karmafun
    id: karmafun
  - env:
      - CGO_ENABLED=1
      # - CC=x86_64-alpine-linux-musl-gcc
      - CC=zig cc -target {{ if (eq .Arch "amd64") }}x86_64-linux-musl{{ else }}aarch64-linux-musl{{ end }} -lunwind
    goos:
      - linux
    # We limit on these architectures because these are the ones for which KCL is provided.
    goarch:
      - amd64
      # FIXME: There is a compilation issue on KCL in musl/arm64
      # - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    tags:
      - musl
    ldflags:
      - -s -w -X main.KarmafunVersion={{.Version}} -X main.Commit={{.Commit}} -X
        main.BuildDate={{ .CommitDate }} -X main.BuiltBy=goreleaser
    binary: karmafun
    id: karmafun_musl
archives:
  - formats: [binary]
    name_template: '{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: "SHA256SUMS"
snapshot:
  version_template: "{{ incpatch .Version }}-devel"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^ci"
      - "^refactor"
      - Merge pull request
      - Merge branch
      - go mod tidy
nfpms:
  - formats: [apk]
    license: Apache 2.0
    package_name: karmafun
    ids:
      - karmafun_musl
    file_name_template: >-
      {{ .PackageName }}-
      {{- .Version }}.
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}
    maintainer: Karmafun <karmafun-devel@karmafun.dev>
    description: KRM function (Kustomize) to decrypt SOPS encoded resources
    homepage: https://github.com/karmafun/karmafun
    bindir: /usr/bin
    apk:
      signature:
        key_file: kaweezle-devel@kaweezle.com-c9d89864.rsa
        key_name: kaweezle-devel@kaweezle.com-c9d89864.rsa.pub
release:
  extra_files:
    - glob: ./kaweezle-devel@kaweezle.com-c9d89864.rsa.pub
dockers_v2:
  - images:
      - "ghcr.io/karmafun/karmafun"
    tags:
      - latest
      - "{{ .Version }}"
    ids:
      - karmafun_musl
    platforms:
      - linux/amd64
      # - linux/arm64
    dockerfile: Dockerfile
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "{{ .ProjectName }}"
      "org.opencontainers.image.url": "https://github.com/karmafun/karmafun"
      "org.opencontainers.image.source": "https://github.com/karmafun/karmafun"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": '{{ time "2006-01-02T15:04:05Z07:00" }}'
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.licenses": "Apache-2.0"
scoops:
  - repository:
      owner: kaweezle
      name: scoop-bucket
      branch: main
      token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
    commit_author:
      name: Karmafun Bot
      email: karmafun-devel@karmafun.dev
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/karmafun/karmafun
    description: "Kustomize SOPS KRM function"
    license: Apache-2.0
