creation_rules:
  - path_regex: .*\.sops\.yaml
    encrypted_regex: "^(data|stringData)$"
    age: age166k86d56ejs2ydvaxv2x3vl3wajny6l52dlkncf2k58vztnlecjs0g5jqq
stores:
  json:
    indent: 2
  json_binary:
    indent: 2
  yaml:
    indent: 2
